name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Checkout repository
        uses: actions/checkout@v1
      - name: ğŸ–¥ï¸ Compile LaTeX document
        uses: vinay0410/tectonic-action@v1.1.2
        with:
          tex_path: cv/cv.tex
          push: yes 
