name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Checkout repository
        uses: actions/checkout@v1
      - name: âœˆï¸ Change Directory
        run: cd cv
      - name: ğŸ–¥ï¸ Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: cv.tex
